# Generated by Django 5.1.2 on 2025-02-20 05:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=128, null=True)),
                ('nombreusuario', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('imagenperfil', models.ImageField(blank=True, null=True, upload_to='perfilUsuarioimagen/')),
                ('activo', models.BooleanField(default=1)),
                ('departamento', models.CharField(blank=True, max_length=128, null=True)),
                ('provincia', models.CharField(blank=True, max_length=128, null=True)),
                ('distrito', models.CharField(blank=True, max_length=128, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idcupon', models.BigAutoField(db_column='idCupon', primary_key=True, serialize=False)),
                ('cantidaddescuento', models.FloatField()),
                ('tipocupon', models.CharField(choices=[('DINERO', 'Dinero'), ('PORCENTAJE', 'Porcentaje')], max_length=10, verbose_name='Tipo de Cupon')),
                ('codigo', models.CharField(max_length=128)),
                ('fechavigencia', models.DateTimeField(blank=True, null=True)),
                ('fechacaducacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cupon',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='marca/')),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idmoneda', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idpromocion', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagenpromocion', models.ImageField(upload_to='promocion/')),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='TblCarrusel',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='slider/')),
                ('titulo', models.CharField(max_length=225)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechapublicacion', models.DateTimeField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblCarrusel',
            },
        ),
        migrations.CreateModel(
            name='Tblcategoria',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('imagen', models.FileField(blank=True, null=True, upload_to='iconoProiedad/')),
            ],
            options={
                'db_table': 'TblCategoria',
            },
        ),
        migrations.CreateModel(
            name='Tblitem',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('codigosku', models.CharField(db_column='codigoSKU', max_length=25, unique=True)),
                ('titulo', models.CharField(max_length=128)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idproduct', models.BigAutoField(primary_key=True, serialize=False)),
                ('destacado', models.BooleanField()),
                ('agotado', models.BooleanField(blank=True, null=True)),
                ('nuevoproducto', models.BooleanField()),
                ('preciorebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('precionormal', models.DecimalField(decimal_places=2, max_digits=20)),
                ('imagenprincipal', models.ImageField(blank=True, null=True, upload_to='imagenPrincipalItem/')),
                ('fechapublicacion', models.DateTimeField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('profundidad', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('ancho', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblItem',
            },
        ),
        migrations.CreateModel(
            name='Tblitemclase',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idclase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tblItemClase',
            },
        ),
        migrations.CreateModel(
            name='Tblnoticia',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('estado', models.IntegerField()),
                ('idnoticia', models.BigAutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=225)),
                ('imagennoticia', models.ImageField(blank=True, null=True, upload_to='imagenNoticia/')),
                ('descripcion', models.TextField()),
                ('fechapublicacion', models.DateTimeField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblNoticia',
            },
        ),
        migrations.CreateModel(
            name='Tblsede',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('direccion', models.TextField()),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('distrito', models.CharField(blank=True, max_length=100, null=True, verbose_name='Distrito')),
                ('telefono', models.CharField(max_length=20, verbose_name='Celular o Teléfono')),
                ('linkmaps', models.URLField(blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenessede/')),
            ],
            options={
                'db_table': 'Tblsede',
            },
        ),
        migrations.CreateModel(
            name='tblTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion_id', models.CharField(max_length=50, unique=True)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('nombre_en_tarjeta', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tblcarrito',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idusuario', models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preciototal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblCarrito',
            },
        ),
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(max_length=128)),
                ('ruc', models.BigIntegerField()),
                ('telefono', models.BigIntegerField()),
                ('igv', models.BigIntegerField()),
                ('datospasarela', models.TextField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idmoneda', models.ForeignKey(blank=True, db_column='idmoneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'Administracion',
            },
        ),
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('iddepartamento', models.CharField(choices=[('01', 'Amazonas'), ('02', 'Áncash'), ('03', 'Apurímac'), ('04', 'Arequipa'), ('05', 'Ayacucho'), ('06', 'Cajamarca'), ('07', 'Callao'), ('08', 'Cusco'), ('09', 'Huancavelica'), ('10', 'Huánuco'), ('11', 'Ica'), ('12', 'Junín'), ('13', 'La Libertad'), ('14', 'Lambayeque'), ('15', 'Lima'), ('16', 'Loreto'), ('17', 'Madre de Dios'), ('18', 'Moquegua'), ('19', 'Pasco'), ('20', 'Piura'), ('21', 'Puno'), ('22', 'San Martín'), ('23', 'Tacna'), ('24', 'Tumbes'), ('25', 'Ucayali')], max_length=2, verbose_name='Departamento')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('idcategoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tblcategoria')),
            ],
            options={
                'db_table': 'Flete',
            },
        ),
        migrations.CreateModel(
            name='Tblimagenitem',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idimagen', models.BigAutoField(db_column='idImagen', primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='imagenesitem/')),
                ('estado', models.IntegerField()),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblImagenItem',
            },
        ),
        migrations.CreateModel(
            name='tblitemcategoria',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(db_column='tblitemcategoria', primary_key=True, serialize=False)),
                ('idcategoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tblcategoria')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_relacionada', to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblitemcategoria',
            },
        ),
        migrations.CreateModel(
            name='tblitemcupon',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('idcupon', models.ForeignKey(blank=True, db_column='idcupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cupon_relacionado', to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemCupon',
            },
        ),
        migrations.CreateModel(
            name='Tblitempropiedad',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idpropiedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('icono', models.FileField(blank=True, null=True, upload_to='iconoProiedad/')),
                ('idclase', models.ForeignKey(blank=True, db_column='idclase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemclase')),
            ],
            options={
                'db_table': 'tblItemPropiedad',
            },
        ),
        migrations.CreateModel(
            name='Tblmodelo',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('idmarca', models.ForeignKey(blank=True, db_column='idmarca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
            ],
            options={
                'db_table': 'TblModelo',
            },
        ),
        migrations.AddField(
            model_name='tblitem',
            name='idmodelo',
            field=models.ForeignKey(blank=True, db_column='idmodelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblmodelo'),
        ),
        migrations.CreateModel(
            name='Tblpedido',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('tipoid', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=20)),
                ('nroid', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('celular', models.CharField(max_length=20, verbose_name='Celular o Teléfono')),
                ('RUC', models.CharField(blank=True, max_length=20, null=True)),
                ('razonsocial', models.TextField(blank=True, null=True)),
                ('tipoenvio', models.IntegerField(blank=True, choices=[(1, 'Envio a domicilio'), (2, 'Recojo en Tienda')], null=True)),
                ('departamento', models.CharField(blank=True, max_length=250, null=True)),
                ('provincia', models.CharField(blank=True, max_length=250, null=True)),
                ('distrito', models.CharField(blank=True, max_length=250, null=True)),
                ('idpedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.FloatField()),
                ('direcciondestino', models.TextField(blank=True, null=True)),
                ('total', models.FloatField()),
                ('igv', models.FloatField(blank=True, null=True)),
                ('totaldescuento', models.FloatField()),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idcliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('idmoneda', models.ForeignKey(db_column='idmoneda', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
                ('idsede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblsede')),
                ('idtransaccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tbltransaccion')),
            ],
            options={
                'db_table': 'TblPedido',
            },
        ),
        migrations.CreateModel(
            name='Tblreclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=25)),
                ('nroid', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=20, verbose_name='Celular o Teléfono')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('tipo_bien', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], max_length=10, verbose_name='Tipo de Bien Contratado')),
                ('numero_pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Pedido')),
                ('monto_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pedido')),
                ('descripcion_bien', models.TextField(verbose_name='Descripción del Bien Contratado')),
                ('tipo_reclamo', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('QUEJA', 'Queja')], max_length=10, verbose_name='Tipo de Reclamo')),
                ('descripcion_reclamo', models.TextField(verbose_name='Descripción del Reclamo o Queja')),
                ('pedido_consumidor', models.TextField(verbose_name='Pedido del Consumidor')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=1)),
                ('estado', models.IntegerField(default=0)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('idsede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblsede')),
            ],
        ),
        migrations.CreateModel(
            name='Tipocambio',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('tipocambio', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('idcambio', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idmoneda', models.ForeignKey(blank=True, db_column='idmoneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'TipoCambio',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('estrellas', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('idvaloracion', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BigIntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
                ('iduser', models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Valoracion',
            },
        ),
        migrations.CreateModel(
            name='tblitemclasevinculo',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('propiedad', models.CharField(max_length=225)),
                ('idclase', models.ForeignKey(db_column='idclase', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='ecommerce.tblitemclase')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.CASCADE, related_name='clases_propiedades', to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemClaseVinculo',
                'unique_together': {('idclase', 'iditem')},
            },
        ),
        migrations.CreateModel(
            name='Tblitemrelacionado',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionados', to='ecommerce.tblitem')),
                ('item_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacionados_por', to='ecommerce.tblitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'item_relacionado'), name='unique_item_relacion')],
            },
        ),
        migrations.CreateModel(
            name='Tbldetallepedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=1)),
                ('precioflete', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cantidad', models.IntegerField()),
                ('preciototal', models.FloatField()),
                ('preciunitario', models.FloatField()),
                ('preciorebajado', models.FloatField()),
                ('idproduct', models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
                ('idpedido', models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblpedido')),
            ],
            options={
                'db_table': 'tbldetallepedido',
                'unique_together': {('idpedido', 'idproduct')},
            },
        ),
        migrations.CreateModel(
            name='Tbldetallecarrito',
            fields=[
                ('activo', models.BooleanField(default=1)),
                ('idproduct', models.OneToOneField(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblitem')),
                ('cantidad', models.BigIntegerField()),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('isuser', models.ForeignKey(db_column='isUser', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblcarrito')),
            ],
            options={
                'db_table': 'tblDetalleCarrito',
                'unique_together': {('idproduct', 'isuser')},
            },
        ),
    ]
