# Generated by Django 5.1.2 on 2024-11-09 19:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=128, null=True)),
                ('nombreusuario', models.CharField(max_length=128, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('email_verified_at', models.DateTimeField(blank=True, null=True)),
                ('remember_token', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreempresa', models.BigIntegerField()),
                ('ruc', models.BigIntegerField()),
                ('telefono', models.BigIntegerField()),
                ('igv', models.BigIntegerField()),
                ('moneda', models.BigIntegerField(blank=True, null=True)),
                ('datospasarela', models.TextField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Administracion',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('idcupon', models.BigAutoField(db_column='idCupon', primary_key=True, serialize=False)),
                ('cantidaddescuento', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechavigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Cupon',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('imgen', models.TextField()),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idmoneda', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagenpromocion', models.TextField(db_column='imagenPromocion')),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='Tblitem',
            fields=[
                ('codigosku', models.CharField(db_column='codigoSKU', max_length=25, unique=True)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('idproduct', models.BigAutoField(primary_key=True, serialize=False)),
                ('destacado', models.BooleanField()),
                ('agotado', models.BooleanField(blank=True, null=True)),
                ('nuevoproducto', models.BooleanField()),
                ('preciorebajado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('precionormal', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idmarca', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
            ],
            options={
                'db_table': 'TblItem',
            },
        ),
        migrations.CreateModel(
            name='Tblpedido',
            fields=[
                ('idpedido', models.BigAutoField(primary_key=True, serialize=False)),
                ('subtotal', models.TextField()),
                ('direcciondestino', models.TextField()),
                ('total', models.TextField()),
                ('igv', models.FloatField(blank=True, null=True)),
                ('totaldescuento', models.FloatField()),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idcliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('idmoneda', models.ForeignKey(db_column='idmoneda', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'TblPedido',
            },
        ),
        migrations.CreateModel(
            name='Tblitemclase',
            fields=[
                ('idclase', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tblItemClase',
            },
        ),
        migrations.CreateModel(
            name='Tblnoticia',
            fields=[
                ('estado', models.IntegerField()),
                ('idnoticia', models.BigAutoField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('imagennoticia', models.TextField(db_column='imagenNoticia')),
                ('descripcion', models.TextField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblNoticia',
            },
        ),
        migrations.CreateModel(
            name='Tblslider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.BigIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblSlider',
            },
        ),
        migrations.CreateModel(
            name='Tblcarrito',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('preciototal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblCarrito',
            },
        ),
        migrations.CreateModel(
            name='Tblimagenitem',
            fields=[
                ('idimagen', models.BigAutoField(db_column='idImagen', primary_key=True, serialize=False)),
                ('imagen', models.TextField()),
                ('estado', models.IntegerField()),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblImagenItem',
            },
        ),
        migrations.CreateModel(
            name='Tblitempropiedad',
            fields=[
                ('idpropiedad', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('idclase', models.ForeignKey(blank=True, db_column='idclase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemclase')),
            ],
            options={
                'db_table': 'tblItemPropiedad',
            },
        ),
        migrations.CreateModel(
            name='Tblitemclasepropiedad',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('idclase', models.ForeignKey(blank=True, db_column='idclase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemclase')),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
                ('idpropiedad', models.ForeignKey(blank=True, db_column='idpropiedad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitempropiedad')),
            ],
            options={
                'db_table': 'tblItemClasePropiedad',
            },
        ),
        migrations.CreateModel(
            name='Tblitemrelacionado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fk', models.ForeignKey(blank=True, db_column='FK_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemrelacionado')),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemRelacionado',
            },
        ),
        migrations.CreateModel(
            name='Tipocambio',
            fields=[
                ('tipocambio', models.BigIntegerField(blank=True, null=True)),
                ('idcambio', models.BigAutoField(primary_key=True, serialize=False)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idmoneda', models.ForeignKey(blank=True, db_column='idmoneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'TipoCambio',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('estrellas', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('idvaloracion', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.BigIntegerField()),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
                ('iduser', models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Valoracion',
            },
        ),
        migrations.CreateModel(
            name='Tbldetallecarrito',
            fields=[
                ('idproduct', models.OneToOneField(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblitem')),
                ('cantidad', models.BigIntegerField()),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('isuser', models.ForeignKey(db_column='isUser', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblcarrito')),
            ],
            options={
                'db_table': 'tblDetalleCarrito',
                'unique_together': {('idproduct', 'isuser')},
            },
        ),
        migrations.CreateModel(
            name='Tbldetallepedido',
            fields=[
                ('idpedido', models.OneToOneField(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblpedido')),
                ('cantidad', models.IntegerField()),
                ('preciototal', models.TextField()),
                ('preciunitario', models.TextField()),
                ('idproduct', models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tbldetallepedido',
                'unique_together': {('idpedido', 'idproduct')},
            },
        ),
    ]
