# Generated by Django 5.1.2 on 2024-10-31 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administracion',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombreempresa', models.BigIntegerField()),
                ('ruc', models.BigIntegerField()),
                ('telefono', models.BigIntegerField()),
                ('igv', models.BigIntegerField()),
                ('moneda', models.BigIntegerField(blank=True, null=True)),
                ('datospasarela', models.TextField()),
            ],
            options={
                'db_table': 'Administracion',
            },
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('idcupon', models.BigIntegerField(db_column='idCupon', primary_key=True, serialize=False)),
                ('cantidaddescuento', models.FloatField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fechavigencia', models.DateTimeField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Cupon',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('imgen', models.TextField()),
            ],
            options={
                'db_table': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('idmoneda', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Moneda',
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('idpromocion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imagenpromocion', models.TextField(db_column='imagenPromocion')),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'Promocion',
            },
        ),
        migrations.CreateModel(
            name='Tblusuario',
            fields=[
                ('idusuario', models.BigIntegerField(db_column='idUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=128, null=True)),
                ('apellido', models.CharField(blank=True, max_length=128, null=True)),
                ('nombreusuario', models.CharField(max_length=128)),
                ('correo', models.CharField(max_length=128)),
                ('direccion', models.CharField(blank=True, max_length=128, null=True)),
                ('contrasenia', models.CharField(max_length=128)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'TblUsuario',
            },
        ),
        migrations.CreateModel(
            name='Tblpedido',
            fields=[
                ('idpedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('subtotal', models.TextField()),
                ('direcciondestino', models.TextField()),
                ('total', models.TextField()),
                ('igv', models.FloatField(blank=True, null=True)),
                ('totaldescuento', models.FloatField()),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
                ('idcliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblusuario')),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('idmoneda', models.ForeignKey(db_column='idmoneda', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'TblPedido',
            },
        ),
        migrations.CreateModel(
            name='Tblimagenitem',
            fields=[
                ('idimagen', models.BigIntegerField(db_column='idImagen', primary_key=True, serialize=False)),
                ('imagen', models.TextField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'tblImagenItem',
            },
        ),
        migrations.CreateModel(
            name='Tblitemclase',
            fields=[
                ('idclase', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'tblItemClase',
            },
        ),
        migrations.CreateModel(
            name='Tblnoticia',
            fields=[
                ('estado', models.IntegerField()),
                ('idnoticia', models.BigIntegerField(db_column='idNoticia', primary_key=True, serialize=False)),
                ('imagennoticia', models.TextField(db_column='imagenNoticia')),
                ('descripcion', models.TextField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'TblNoticia',
            },
        ),
        migrations.CreateModel(
            name='Tblslider',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('imagen', models.BigIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'TblSlider',
            },
        ),
        migrations.CreateModel(
            name='Tblcarrito',
            fields=[
                ('idusuario', models.OneToOneField(db_column='idUsuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblusuario')),
                ('preciototal', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'TblCarrito',
            },
        ),
        migrations.CreateModel(
            name='Tblitem',
            fields=[
                ('codigosku', models.CharField(db_column='codigoSKU', max_length=25, unique=True)),
                ('pliegues', models.CharField(blank=True, max_length=20, null=True)),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('idproduct', models.BigIntegerField(primary_key=True, serialize=False)),
                ('rangovelocidad', models.CharField(blank=True, max_length=20, null=True)),
                ('destacado', models.BooleanField()),
                ('agotado', models.BooleanField(blank=True, null=True)),
                ('nuevoproducto', models.BooleanField()),
                ('preciorebajado', models.TextField(blank=True, null=True)),
                ('precionormal', models.TextField()),
                ('estado', models.IntegerField()),
                ('fechacreacion', models.DateTimeField()),
                ('fechamodificacion', models.DateTimeField()),
                ('id', models.ForeignKey(blank=True, db_column='id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
                ('idimagen', models.ForeignKey(blank=True, db_column='idImagen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblimagenitem')),
            ],
            options={
                'db_table': 'TblItem',
            },
        ),
        migrations.CreateModel(
            name='Tblitemclasepropiedad',
            fields=[
                ('id', models.BigIntegerField(db_column='Id', primary_key=True, serialize=False)),
                ('idclase', models.ForeignKey(blank=True, db_column='idclase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemclase')),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemClasePropiedad',
            },
        ),
        migrations.CreateModel(
            name='Tblitempropiedad',
            fields=[
                ('idpropiedad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.BigIntegerField(blank=True, null=True)),
                ('idclase', models.ForeignKey(blank=True, db_column='idclase', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemclase')),
            ],
            options={
                'db_table': 'tblItemPropiedad',
            },
        ),
        migrations.CreateModel(
            name='Tblitemrelacionado',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fk', models.ForeignKey(blank=True, db_column='FK_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitemrelacionado')),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemRelacionado',
            },
        ),
        migrations.CreateModel(
            name='Tipocambio',
            fields=[
                ('tipocambio', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.BigIntegerField(blank=True, null=True)),
                ('idcambio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('idmoneda', models.ForeignKey(blank=True, db_column='idmoneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda')),
            ],
            options={
                'db_table': 'TipoCambio',
            },
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('estrellas', models.BigIntegerField(blank=True, null=True)),
                ('comentario', models.TextField()),
                ('idvaloracion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('estado', models.BigIntegerField()),
                ('datecreation', models.DateTimeField()),
                ('telefono', models.BigIntegerField(blank=True, null=True)),
                ('fechamodificacion', models.TimeField()),
                ('idproduct', models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
                ('iduser', models.ForeignKey(blank=True, db_column='idUser', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblusuario')),
            ],
            options={
                'db_table': 'Valoracion',
            },
        ),
        migrations.CreateModel(
            name='Tbldetallecarrito',
            fields=[
                ('idproduct', models.OneToOneField(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblitem')),
                ('cantidad', models.BigIntegerField()),
                ('idcupon', models.ForeignKey(blank=True, db_column='idCupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('isuser', models.ForeignKey(db_column='isUser', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblcarrito')),
            ],
            options={
                'db_table': 'tblDetalleCarrito',
                'unique_together': {('idproduct', 'isuser')},
            },
        ),
        migrations.CreateModel(
            name='Tbldetallepedido',
            fields=[
                ('idpedido', models.OneToOneField(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblpedido')),
                ('cantidad', models.IntegerField()),
                ('preciototal', models.TextField()),
                ('preciunitario', models.TextField()),
                ('idproduct', models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tbldetallepedido',
                'unique_together': {('idpedido', 'idproduct')},
            },
        ),
    ]
