# Generated by Django 5.1.2 on 2024-11-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitem',
            name='idimagen',
        ),
        migrations.AddField(
            model_name='tblimagenitem',
            name='idproduct',
            field=models.ForeignKey(blank=True, db_column='idproduct', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem'),
        ),
        migrations.AlterField(
            model_name='administracion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cupon',
            name='idcupon',
            field=models.BigAutoField(db_column='idCupon', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='idmoneda',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='idpromocion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblimagenitem',
            name='idimagen',
            field=models.BigAutoField(db_column='idImagen', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='idproduct',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblitemclase',
            name='idclase',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblitemclasepropiedad',
            name='id',
            field=models.BigAutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblitempropiedad',
            name='idpropiedad',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblitemrelacionado',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblnoticia',
            name='idnoticia',
            field=models.BigAutoField(db_column='idNoticia', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='idpedido',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblslider',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblusuario',
            name='idusuario',
            field=models.BigAutoField(db_column='idUsuario', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tipocambio',
            name='idcambio',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='valoracion',
            name='idvaloracion',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
