# Generated by Django 5.1.2 on 2025-03-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='simbolo',
            field=models.CharField(default='S', max_length=20),
            preserve_default=False,
        ),
    ]
