# Generated by Django 5.1.2 on 2024-11-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_tblitem_idimagen_tblimagenitem_idproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitem',
            name='pliegues',
        ),
    ]
