# Generated by Django 5.1.2 on 2024-11-20 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_administracion_moneda_administracion_idmoneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitemclasepropiedad',
            name='idproduct',
            field=models.ForeignKey(db_column='idproduct', on_delete=django.db.models.deletion.DO_NOTHING, related_name='clases_propiedades', to='ecommerce.tblitem'),
        ),
    ]
