# Generated by Django 5.1.2 on 2024-11-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_remove_tblitem_pliegues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitem',
            name='rangovelocidad',
        ),
    ]
