# Generated by Django 5.1.2 on 2024-11-06 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_remove_tblitem_rangovelocidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitem',
            name='precionormal',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='preciorebajado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
