# Generated by Django 5.1.2 on 2024-11-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_alter_tblitemclasepropiedad_idproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
