# Generated by Django 5.1.2 on 2024-11-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_tblitem_precionormal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblitem',
            old_name='id',
            new_name='idmarca',
        ),
        migrations.AlterField(
            model_name='tblitempropiedad',
            name='nombre',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
