# Generated by Django 5.1.2 on 2024-11-06 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_rename_id_tblitem_idmarca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitemclasepropiedad',
            name='idpropiedad',
            field=models.ForeignKey(blank=True, db_column='idpropiedad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitempropiedad'),
        ),
    ]
