# Generated by Django 5.1.2 on 2024-11-23 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_rename_numero_customuser_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='departamento',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='distrito',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provincia',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
