# Generated by Django 5.1.2 on 2024-11-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_customuser_departamento_customuser_distrito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitem',
            name='imagenprincipal',
            field=models.ImageField(blank=True, null=True, upload_to='imagenPrincipalItem/'),
        ),
        migrations.AddField(
            model_name='tblitemclase',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconoClase/'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='imgen',
            field=models.ImageField(blank=True, null=True, upload_to='marca/'),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='imagenpromocion',
            field=models.ImageField(upload_to='promocion/'),
        ),
        migrations.AlterField(
            model_name='tblimagenitem',
            name='imagen',
            field=models.ImageField(upload_to='imagenesitem/'),
        ),
        migrations.AlterField(
            model_name='tblslider',
            name='imagen',
            field=models.ImageField(upload_to='slider/'),
        ),
    ]
