# Generated by Django 5.1.2 on 2024-11-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_tblitem_imagenprincipal_tblitemclase_icono_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitemclase',
            name='icono',
        ),
        migrations.AddField(
            model_name='tblitempropiedad',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='iconoProiedad/'),
        ),
    ]
