# Generated by Django 5.1.2 on 2024-12-06 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_alter_tblitem_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblitemcupon',
            fields=[
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('idcupon', models.ForeignKey(blank=True, db_column='idcupon', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.cupon')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cupon_relacionado', to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemCupon',
            },
        ),
    ]
