# Generated by Django 5.1.2 on 2024-12-06 00:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_tblitemcupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitem',
            name='fechapublicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
