# Generated by Django 5.1.2 on 2024-12-09 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_tblitem_altura_alter_tblitem_ancho_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitemrelacionado',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='tblitemrelacionado',
            name='idproduct',
        ),
        migrations.AddField(
            model_name='tblitemrelacionado',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relacionados', to='ecommerce.tblitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblitemrelacionado',
            name='producto_relacionado',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='relacionados_por', to='ecommerce.tblitem'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tblitemrelacionado',
            constraint=models.UniqueConstraint(fields=('producto', 'producto_relacionado'), name='unique_producto_relacion'),
        ),
    ]
