# Generated by Django 5.1.2 on 2024-12-09 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_remove_tblitemrelacionado_unique_producto_relacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tblitemrelacionado',
            old_name='producto',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='tblitemrelacionado',
            old_name='producto_relacionado',
            new_name='item_relacionado',
        ),
        migrations.AlterUniqueTogether(
            name='tblitemrelacionado',
            unique_together={('item', 'item_relacionado')},
        ),
    ]
