# Generated by Django 5.1.2 on 2024-12-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_rename_imgen_marca_imagen_remove_tblitem_idmarca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tblitemclasevinculo',
            fields=[
                ('activo', models.BooleanField()),
                ('id', models.BigAutoField(db_column='Id', primary_key=True, serialize=False)),
                ('propiedad', models.CharField(max_length=225)),
                ('idclase', models.ForeignKey(db_column='idclase', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tblitemclase')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.CASCADE, related_name='clases_propiedades', to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblItemClaseVinculo',
            },
        ),
        migrations.DeleteModel(
            name='Tblitemclasepropiedad',
        ),
    ]
