# Generated by Django 5.1.2 on 2024-12-18 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_alter_administracion_activo_alter_cupon_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblcategoria',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Categoria/')),
            ],
            options={
                'db_table': 'TblCategoria',
            },
        ),
        migrations.CreateModel(
            name='tblitemcategoria',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('id', models.BigAutoField(db_column='tblitemcategoria', primary_key=True, serialize=False)),
                ('idcategoria', models.ForeignKey(db_column='idcategoria', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tblcategoria')),
                ('iditem', models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.CASCADE, to='ecommerce.tblitem')),
            ],
            options={
                'db_table': 'tblitemcategoria',
            },
        ),
    ]
