# Generated by Django 5.1.2 on 2024-12-19 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0031_alter_tblitemcategoria_iditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tblsede',
            fields=[
                ('activo', models.BooleanField(default=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'Tblsede',
            },
        ),
        migrations.AddField(
            model_name='tipocambio',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valoracion',
            name='pasarela',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tblreclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoid', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=25)),
                ('nroid', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('telefono', models.CharField(max_length=20, verbose_name='Celular o Teléfono')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('provincia', models.CharField(max_length=100, verbose_name='Provincia')),
                ('distrito', models.CharField(max_length=100, verbose_name='Distrito')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('tipo_bien', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio')], max_length=10, verbose_name='Tipo de Bien Contratado')),
                ('numero_pedido', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Pedido')),
                ('monto_pedido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Pedido')),
                ('descripcion_bien', models.TextField(verbose_name='Descripción del Bien Contratado')),
                ('tipo_reclamo', models.CharField(choices=[('RECLAMO', 'Reclamo'), ('QUEJA', 'Queja')], max_length=10, verbose_name='Tipo de Reclamo')),
                ('descripcion_reclamo', models.TextField(verbose_name='Descripción del Reclamo o Queja')),
                ('pedido_consumidor', models.TextField(verbose_name='Pedido del Consumidor')),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('idsede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblsede')),
            ],
        ),
    ]
