# Generated by Django 5.1.2 on 2024-12-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0034_remove_cupon_descripcion_cupon_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblreclamacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tblreclamacion',
            name='estado',
            field=models.IntegerField(default=0),
        ),
    ]
