# Generated by Django 5.1.2 on 2024-12-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_tblsede_direccion_tblsede_email_tblsede_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocambio',
            name='tipocambio',
            field=models.DecimalField(blank=True, decimal_places=22, max_digits=22, null=True),
        ),
    ]
