# Generated by Django 5.1.2 on 2024-12-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_alter_administracion_nombreempresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='cupon',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='moneda',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='promocion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblcarrito',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblcarrusel',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblcategoria',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tbldetallecarrito',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tbldetallepedido',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblimagenitem',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitem',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitemcategoria',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitemclase',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitemclasevinculo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitemcupon',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitempropiedad',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblitemrelacionado',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblmodelo',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblnoticia',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblpedido',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblreclamacion',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tblsede',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='tipocambio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='activo',
        ),
    ]
