# Generated by Django 5.1.2 on 2024-12-28 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_administracion_activo_cupon_activo_customuser_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='pasarela',
        ),
        migrations.RemoveField(
            model_name='valoracion',
            name='telefono',
        ),
    ]
