# Generated by Django 5.1.2 on 2024-12-29 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0041_remove_valoracion_pasarela_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocambio',
            name='tipocambio',
        ),
    ]
