# Generated by Django 5.1.2 on 2025-01-16 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0046_tblpedido_apellidos_tblpedido_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbldetallepedido',
            name='idpedido',
            field=models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecommerce.tblpedido'),
        ),
    ]
