# Generated by Django 5.1.2 on 2025-01-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_tblpedido_departamento_tblpedido_distrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpedido',
            name='tipoid',
            field=models.IntegerField(choices=[('1', 'Envio a domicilio'), ('2', 'Recojo en Tienda')]),
        ),
    ]
