# Generated by Django 5.1.2 on 2025-01-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0052_tblpedido_ruc_tblpedido_idsede_tblpedido_razonsocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpedido',
            name='tipoenvio',
            field=models.IntegerField(choices=[(1, 'Envio a domicilio'), (2, 'Recojo en Tienda')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='tipoid',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC')], max_length=20),
        ),
    ]
