# Generated by Django 5.1.2 on 2025-01-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0053_tblpedido_tipoenvio_alter_tblpedido_tipoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblsede',
            name='linkmaps',
            field=models.URLField(blank=True),
        ),
    ]
