# Generated by Django 5.1.2 on 2025-01-18 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0056_transaccion_tblpedido_idtransaccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaccion',
            new_name='tblTransaccion',
        ),
    ]
