# Generated by Django 5.1.2 on 2025-01-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0057_rename_transaccion_tbltransaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbldetallepedido',
            name='idflete',
        ),
        migrations.AddField(
            model_name='tbldetallepedido',
            name='precioflete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
