# Generated by Django 5.1.2 on 2025-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0058_remove_tbldetallepedido_idflete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpedido',
            name='departamento',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='distrito',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='provincia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='tipoenvio',
            field=models.IntegerField(blank=True, choices=[(1, 'Envio a domicilio'), (2, 'Recojo en Tienda')], null=True),
        ),
    ]
