# Generated by Django 5.1.2 on 2025-01-24 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0061_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblitemclasevinculo',
            unique_together={('idclase', 'iditem')},
        ),
    ]
