# Generated by Django 5.1.2 on 2025-02-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0062_alter_tblitemclasevinculo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitem',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='fechapublicacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
