# Generated by Django 5.1.2 on 2024-11-12 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='tblitemclasepropiedad',
            name='idproduct',
            field=models.ForeignKey(db_column='idproduct', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblitem'),
            preserve_default=False,
        ),
    ]
