# Generated by Django 5.1.2 on 2024-11-13 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_customuser_email_alter_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administracion',
            name='moneda',
        ),
        migrations.AddField(
            model_name='administracion',
            name='idmoneda',
            field=models.ForeignKey(blank=True, db_column='idmoneda', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.moneda'),
        ),
    ]
