# Generated by Django 5.1.2 on 2024-11-23 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_customuser_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='numero',
            new_name='telefono',
        ),
    ]
