# Generated by Django 5.1.2 on 2024-11-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_remove_tblitemclase_icono_tblitempropiedad_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitempropiedad',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='iconoProiedad/'),
        ),
    ]
