# Generated by Django 5.1.2 on 2024-11-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_tblitempropiedad_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblitem',
            name='idmarca',
        ),
    ]
