# Generated by Django 5.1.2 on 2024-11-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_customuser_imagenperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblitem',
            name='titulo',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
