# Generated by Django 5.1.2 on 2024-11-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0013_tblitem_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitem',
            name='titulo',
            field=models.CharField(default='titulo def', max_length=128),
            preserve_default=False,
        ),
    ]
