# Generated by Django 5.1.2 on 2024-12-07 01:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_tblitem_fechapublicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblCarrusel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='slider/')),
                ('titulo', models.CharField(max_length=225)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.IntegerField()),
                ('fechapublicacion', models.DateTimeField()),
                ('fechacreacion', models.DateTimeField(auto_now_add=True)),
                ('fechamodificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'TblCarrusel',
            },
        ),
        migrations.DeleteModel(
            name='Tblslider',
        ),
        migrations.AddField(
            model_name='tblnoticia',
            name='fechapublicacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblnoticia',
            name='titulo',
            field=models.CharField(default='titulo text', max_length=225),
            preserve_default=False,
        ),
    ]
