# Generated by Django 5.1.2 on 2024-12-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_tblitem_altura_tblitem_ancho_tblitem_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitem',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='ancho',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='tblitem',
            name='profundidad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
