# Generated by Django 5.1.2 on 2024-12-09 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_remove_tblitemrelacionado_fk_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tblitemrelacionado',
            name='unique_producto_relacion',
        ),
        migrations.AlterUniqueTogether(
            name='tblitemrelacionado',
            unique_together={('producto', 'producto_relacionado')},
        ),
    ]
