# Generated by Django 5.1.2 on 2024-12-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_rename_producto_tblitemrelacionado_item_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tblitemrelacionado',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='tblitemrelacionado',
            constraint=models.UniqueConstraint(fields=('item', 'item_relacionado'), name='unique_item_relacion'),
        ),
        migrations.AlterModelTable(
            name='tblitemrelacionado',
            table=None,
        ),
    ]
