# Generated by Django 5.1.2 on 2024-12-09 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_tblitemrelacionado_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marca',
            old_name='imgen',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='tblitem',
            name='idmarca',
        ),
        migrations.CreateModel(
            name='Tblmodelo',
            fields=[
                ('activo', models.BooleanField()),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=128)),
                ('idmarca', models.ForeignKey(blank=True, db_column='idmarca', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.marca')),
            ],
            options={
                'db_table': 'TblModelo',
            },
        ),
        migrations.AddField(
            model_name='tblitem',
            name='idmodelo',
            field=models.ForeignKey(blank=True, db_column='idmodelo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblmodelo'),
        ),
    ]
