# Generated by Django 5.1.2 on 2024-12-18 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_tblcategoria_tblitemcategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblitemcategoria',
            name='iditem',
            field=models.ForeignKey(db_column='iditem', on_delete=django.db.models.deletion.CASCADE, related_name='categoria_relacionada', to='ecommerce.tblitem'),
        ),
    ]
