# Generated by Django 5.1.2 on 2024-12-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0032_tblsede_tipocambio_fecha_valoracion_pasarela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblnoticia',
            name='imagennoticia',
            field=models.ImageField(blank=True, null=True, upload_to='imagenNoticia/'),
        ),
    ]
