# Generated by Django 5.1.2 on 2024-12-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0033_alter_tblnoticia_imagennoticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupon',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='cupon',
            name='codigo',
            field=models.CharField(default='CODIGO', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cupon',
            name='fechacaducacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
