# Generated by Django 5.1.2 on 2024-12-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_remove_tipocambio_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocambio',
            name='tipocambio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
