# Generated by Django 5.1.2 on 2024-12-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_tipocambio_tipocambio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='tipocupon',
            field=models.CharField(choices=[('DINERO', 'Dinero'), ('PORCENTAJE', 'Porcentaje')], default='DINERO', max_length=10, verbose_name='Tipo de Cupon'),
            preserve_default=False,
        ),
    ]
