# Generated by Django 5.1.2 on 2025-01-16 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_alter_tbldetallepedido_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldetallepedido',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tbldetallepedido',
            name='idpedido',
            field=models.ForeignKey(db_column='idpedido', on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblpedido'),
        ),
    ]
