# Generated by Django 5.1.2 on 2025-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0048_tbldetallepedido_id_alter_tbldetallepedido_idpedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpedido',
            name='departamento',
            field=models.CharField(default='Arequipa', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblpedido',
            name='distrito',
            field=models.CharField(default='Arequipa', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tblpedido',
            name='provincia',
            field=models.CharField(default='Arequipa', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='tipoid',
            field=models.IntegerField(choices=[('1', 'Envio a domicilio'), ('2', 'Recojo en Tienda')], max_length=2),
        ),
    ]
