# Generated by Django 5.1.2 on 2025-01-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0050_alter_tblpedido_tipoid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblpedido',
            name='subtotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tblpedido',
            name='total',
            field=models.FloatField(),
        ),
    ]
