# Generated by Django 5.1.2 on 2025-01-16 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0051_alter_tblpedido_subtotal_alter_tblpedido_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblpedido',
            name='RUC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tblpedido',
            name='idsede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.tblsede'),
        ),
        migrations.AddField(
            model_name='tblpedido',
            name='razonsocial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
