# Generated by Django 5.1.2 on 2025-01-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0055_tbldetallepedido_idflete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaccion_id', models.CharField(max_length=50, unique=True)),
                ('metodo_pago', models.CharField(max_length=20)),
                ('nombre_en_tarjeta', models.CharField(max_length=255)),
                ('numero_tarjeta', models.CharField(max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='tblpedido',
            name='idtransaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ecommerce.transaccion'),
        ),
    ]
